name: Build and Deploy LaTeX Project
permissions: write-all
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Compiles
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tabelas.tex
      
      # Uploads the PDF
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: tabelas.pdf
      
      # Publishes the PDF as a release
      - name: Publish PDF
        uses: softprops/action-gh-release@v2
        with:
          tag_name: current
          files: tabelas.pdf