name: copyrights
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  copyrights:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/copyrights-action@0.0.8
