name: Release LaTeX Project
permissions:
  contents: read
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build Document
    runs-on: ubuntu-24.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Compiles
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: tabelas.tex
      
      # Uploads the PDF
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: tabelas.pdf
          if-no-files-found: error
  
  release:
    name: Release on GitHub
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          files: tabelas.pdf
        
      # Publishes the PDF as a release
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          files: tabelas.pdf