name: yamllint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  yamllint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
